### ISSUE TITLE
evdev: unable to open mapping file ''

### ISSUE THREAD

**Issue by kazukisan** [reicast/reicast-emulator#1001] opened 2017-01-24 05:33 UTC
Linux, Ubuntu 16.04

Even though in ~/.config/reicast/emu.cfg, evdev_device_id_1 and evdev_mapping_1 are properly entered, when starting Reicast with ./reicast-elf, an error looks as following:

```
evdev: Trying to open device at '/dev/input/event15'
evdev: Found 'Sony Interactive Entertainment Wireless Controller' at '/dev/input/event15'
evdev: unable to open mapping file ''
evdev: No such file or directory
evdev: Controller 2 disabled by config.
evdev: Controller 3 disabled by config.
evdev: Controller 4 disabled by config.
Legacy Joystick input disabled by config.
```

Yes, device id is 15, and it looks like Reicast is detecting it correctly, however even though emu.cfg has a properly written absolute path for /home/MY_USER_NAME/.config/reicast/mappings/controller_ds4drv.cfg, I always end up with unable to open mapping file '', message for some reason.

Contents within controller_ds4drv.cfg file looks correct on my end. so I don't think it is cfg file causing this issue, but never sure!

**Comment by daveerwin** [comment] 2017-08-05 23:11
had this same issue, had it setup correctly w/ absolute pate in emu.cfg to the controller.cfg file, but it wouldn't load.
I ended up copying my config into /usr/local/share/reicast/mappings/controller_generic.cfg
and removing the `evdev_mapping_1` from emu.cfg

**Comment by promi** [comment] 2017-12-09 14:43
Duplicate of #1051

**Comment by skmp** [comment] 2018-04-24 22:24
Should be fixed now. Re-open if it still happens

**Closed by skmp** 2018-04-24 22:24 UTC
