### ISSUE TITLE
Libretro port?

### ISSUE THREAD

**Issue by Holzhaus** [reicast/reicast-emulator#630] opened 2015-04-04 17:15 UTC
Hi,

just wondering, is a libretro port planned?
>Software that targets the libretro API instantly gains access to all of the platforms that have libretro frontends available. That means your game is immediately available to those platforms’ users without worrying about input/audio/video drivers, compatibility issues or the myriad quirks of the underlying host system(s). Likewise, there’s no need to write specialized GUI code for each platform or to use esoteric–and often buggy–cross-platform toolkits, like Qt and GTK+.
>
>Furthermore, once your game supports libretro, all of the libretro frontends’ other features come along for free, such as RetroArch’s real-time rewind, lag-concealing netplay, lossless video recording/streaming and cutting-edge post-processing shader support.
>
>Perhaps best of all: libretro is an open specification that is 100% free to implement, with no licensing fees or hidden strings attached.
>*Source: [http://www.libretro.com/index.php/api/](http://www.libretro.com/index.php/api/)*

**Comment by MollyM** [comment] 2015-04-11 15:04
I'd love to see this! It'd make setting up my xbox 360 controller a breeze, which currently doesn't work on my raspberry pi 2 with Reicast.

**Comment by neko68k** [comment] 2015-04-11 15:15
This is a feature request, not a bug. Please only post actual issues. :-)

**Comment by Holzhaus** [comment] 2015-08-30 01:02
I'm going to looking into implementing this, if I may.

Here are some useful documents:
- [libretro.pdf](https://github.com/libretro/libretro.github.com/blob/master/documents/libretro.pdf)
- [libretro-gl.pdf](https://raw.githubusercontent.com/libretro/libretro.github.com/master/documents/libretro-gl.pdf)

**Comment by skmp** [comment] 2015-09-02 02:52
Yes, libretro. Our rendering is async, so you can just use it as it is (and
start a background thread for the main sh4 core). @Twinaphex also wanted to
look into this

On Sun, Aug 30, 2015 at 3:02 AM, Jan Holthuis <notifications@github.com>
wrote:

> I'm going to looking into implementing this, if I may.
>
> Here are some useful documents:
>
>    - libretro.pdf
>    <https://github.com/libretro/libretro.github.com/blob/master/documents/libretro.pdf>
>    - libretro-gl.pdf
>    <https://raw.githubusercontent.com/libretro/libretro.github.com/master/documents/libretro-gl.pdf>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/630#issuecomment-136067071>
> .
>



-- 
~skmp

**Comment by twinaphex** [comment] 2015-09-02 08:28
@Holzhaus Thatd be great and would be really appreciated. I have been bogged down in a lot of work on the RetroArch side right now so itd be great if you could look into this.

**Comment by Holzhaus** [comment] 2015-09-02 16:49
@twinaphex Don't get too excited though:
- I'm a noob (especially when it comes to OpenGL stuff)
- Our GLES/OpenGL rendering code is an unmaintainable mess

I hope I can do the other stuff though.

**Comment by twinaphex** [comment] 2015-09-02 18:24
Just let us know when you have problems with certain bits and we can help you out.

**Comment by hooby3dfx** [comment] 2016-03-28 04:05
updating thread for anyone interested/informational purposes: reicast got added to retroarch a couple months ago:
http://www.libretro.com/index.php/retroarch-1-3-released/

**Comment by mk8itra1n** [comment] 2016-03-28 04:21
I'd love to see Reicast come to RetroArch. I've been waiting ages for the iOS version of it and this may be the big break we've all been waiting for. Go for it👍

**Comment by sabula310** [comment] 2016-03-29 20:14
On Mar 27, 2016 9:22 PM, "mk8itra1n" <notifications@github.com> wrote:
>
> I'd love to see Reicast come to RetroArch. I've been waiting ages for the
iOS version of it and this may be the big break we've all been waiting for.
Go for it👍but will it play  fullspeed  people asked

**Comment by twinaphex** [comment] 2016-09-19 12:50
We can close this issue now too, libretro port has already been done by myself. And apparently after about a year there is no interest whatsoever to have it in upstream, so whatever.

**Closed by twinaphex** 2016-09-19 12:50 UTC
Labels: discussion
