### ISSUE TITLE
Stil have issue on sonic adventure with new reicast master

### ISSUE THREAD

**Issue by dhanial** [reicast/reicast-emulator#1525] opened 2019-03-26 16:54 UTC
MODEL: Redmi Note 4
DEVICE: mido
BOARD: MSM8953
Oreo (27)

Native Interface Output

--------- beginning of system
--------- beginning of main
03-26 23:49:40.398 22297 22297 I reicast : Android: Opened joystick 2 on port 0: 'msm8953-snd-card-mtp Button Jack' 
03-26 23:49:40.399 22297 22297 I reicast : using default mapping
03-26 23:49:40.400 22297 22297 I reicast : Android: Opened joystick 4 on port 0: 'gpio-keys' 
03-26 23:49:40.400 22297 22297 I reicast : using default mapping
03-26 23:49:40.401 22297 22297 I reicast : Android: Opened joystick 5 on port 0: 'qpnp_pon' 
03-26 23:49:40.401 22297 22297 I reicast : using default mapping
03-26 23:49:40.403 22297 22297 I reicast : Android: Opened joystick 7 on port 0: 'gf3208' 
03-26 23:49:40.403 22297 22297 I reicast : using default mapping
03-26 23:49:40.404 22297 22297 I reicast : Android: Opened joystick 9 on port 0: 'ft5435_ts' 
03-26 23:49:40.404 22297 22297 I reicast : using default mapping
03-26 23:49:40.553 22297 22297 I reicast : EGL config: 0x6f6c0caf80, 0x1, 0x6fa5f39100 1920x1080
03-26 23:49:40.553 22297 22297 I reicast : OpenGL version: OpenGL ES 3.2 V@251.0 (GIT@8c8f5af, Ic7262d4df1) (Date:10/28/17)
03-26 23:49:40.685 22297 22297 I reicast : Screen DPI is 399, size 1920 x 1080. Scaling by 2.99
03-26 23:49:50.659 22297 22297 I reicast : SaveAndroidSettings: saving preferences
03-26 23:49:56.085 22297 22297 I reicast : SaveAndroidSettings: saving preferences
03-26 23:49:56.941 22297 22297 I reicast : Loaded /storage/emulated/0/Reicast/data/dc_boot.bin as bootrom
03-26 23:49:56.941 22297 22297 I reicast : 
03-26 23:49:56.942 22297 22297 I reicast : Loaded /storage/emulated/0/Reicast/data/dc_nvmem.bin as nvram
03-26 23:49:56.942 22297 22297 I reicast : 
03-26 23:49:56.951 22297 22297 I reicast : SaveAndroidSettings: saving preferences
03-26 23:49:56.954 22297 22297 I reicast : chd: chd_open failed for file /storage/720A-14F6/Emulator/Console/Dreamcast/Sonic Adventure.cdi: 5
03-26 23:49:56.955 22297 22297 I reicast : Warning: CDI Image Loaded!
03-26 23:49:56.955 22297 22297 I reicast :   Many CDI images are known to be defective, GDI, CUE or CHD format is preferred. Please only file bug reports when using images known to be good (GDI, CUE or CHD).
03-26 23:49:56.955 22297 22297 I reicast : gdrom: Opened image "/storage/720A-14F6/Emulator/Console/Dreamcast/Sonic Adventure.cdi"
03-26 23:49:56.956 22297 22297 I reicast : 
03-26 23:49:56.956 22297 22297 I reicast : 	 ARM7_TCB addr: 0x6f951c8000 | from: 0x6f951c7adc | addr here: 0x6f952c8d84
03-26 23:49:56.980 22297 22297 I reicast : Game ID is [MK-51000]
03-26 23:49:56.980 22297 22297 I reicast : recSh4 Init
03-26 23:49:56.980 22297 22297 I reicast : Freeing fpcb
03-26 23:49:56.980 22297 22297 I reicast : 
03-26 23:49:56.980 22297 22297 I reicast : 	 CodeCache addr: 0x6f95394000 | from: 0x6f95394000 | addr here: 0x6f95d952d4
03-26 23:49:57.004 22297 22297 I reicast : Initializing the ARM64 dynarec
03-26 23:49:57.004 22297 22297 I reicast : Using Recompiler
03-26 23:49:57.010 22297 22297 I reicast : Sh4 Reset
03-26 23:49:57.011 22297 22355 I reicast : Auto-selected audio backend "android" (Android Audio).
03-26 23:49:57.011 22297 22355 I reicast : Initializing audio backend "android" (Android Audio)...
03-26 23:49:57.011 22297 22355 I reicast : Using Recompiler
03-26 23:49:57.011 22297 22355 I reicast : cntx // fpcb offset: -135266304 // pc offset: -184 // pc A0000000
03-26 23:49:57.014 22297 22355 I reicast : Freeing fpcb
03-26 23:49:57.014 22297 22355 I reicast : recSh4:Dynarec Cache clear at 8C0000DE
03-26 23:49:57.068 22297 22355 I reicast : Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
03-26 23:49:57.069 22297 22355 I reicast : MODEM Reset
03-26 23:49:57.071 22297 22355 I reicast : VREG = 02 ARMRST 00
03-26 23:49:57.081 22297 22355 I reicast : VREG = 02 ARMRST 01
03-26 23:49:57.112 22297 22355 I reicast : VREG = 02 ARMRST 00
03-26 23:49:57.256 22297 22355 I reicast : Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
03-26 23:

**Comment by flyinghead** [comment] 2019-03-26 16:57
Duplicate of issue #1521. Please explain your problem there so we can help.

**Closed by flyinghead** 2019-03-26 16:57 UTC

**Comment by dhanial** [comment] 2019-03-26 17:02
Issue it's still same as latest version of fh_mymaster reicast still have
weird graphic in sonic adventure, game sound and sfx is normal but not in
graphic i have redownload bios and delete cfg file nothing change sorry i
have a bad english
