### ISSUE TITLE
Fix VS2017 build errors

### ISSUE THREAD

**Issue by Souzooka** [reicast/reicast-emulator#1147] opened 2018-05-07 07:39 UTC
When attempting to compile a x64 build of the Reicast master branch for Windows in Visual Studio 2017, the compiler generates C2894 errors ("templates cannot be declared to have 'C' linkage") with the external dependency xtr1common file.

**Comment by LoungeKatt** [comment] 2018-05-07 11:02
It probably has something to do with the source only being updated for VS 2015.

**Comment by skmp** [comment] 2018-05-11 15:29
I guess we need to migrate sooner or later

**Comment by skmp** [comment] 2018-05-11 16:36
@Souzooka do you want to tackle this issue? We would appreciate your contribution :3 :3 https://github.com/reicast/reicast-emulator/#contributing

**Comment by PeteBurgess** [comment] 2018-07-17 15:18
Are there build instructions for Windows anywhere ?

**Comment by weihuoya** [comment] 2018-07-17 15:22
It's like this, Include header fx for vs2015 #1177

**Comment by PeteBurgess** [comment] 2018-07-17 17:35
That fixed it, thanks. Is it worth fixing the "converted int32 to int" type stuff or is that by design ?

**Comment by skmp** [comment] 2020-04-02 13:40
VS 2019 + CMAKELISTS is the current build env, and it works now. Closing....

**Closed by skmp** 2020-04-02 13:40 UTC
Labels: Good First Issue, Help Wanted
