### ISSUE TITLE
Can't keep Lt and Rt buttons pressed.

### ISSUE THREAD

**Issue by blackman91** [reicast/reicast-emulator#1294] opened 2018-08-16 01:50 UTC
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Android 7 | Google Play Beta | b2e07d0| Downloaded from build site? No |

**_Description of the Issue_**

Using an external gamepad you can't keep both Lt and Rt buttons pressed at the same time, they both get pressed for a second then Lt loses its pressed state, you can test this by touching the screen during gameplay so the touchscreen overlay appears and press both Lt and Rt and mantain them pressed, you can see how Lt doesn't keep pressed even when you are still pressing both buttons on the gamepad.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [x] Place an X in the box to confirm you have filled in this form

**Comment by AbandonedCart** [comment] 2018-08-16 03:00
Duplicate of https://github.com/reicast/reicast-emulator/issues/998

**Closed by AbandonedCart** 2018-08-16 03:00 UTC
