### ISSUE TITLE
LT and RT HID gamepad still not working

### ISSUE THREAD

**Issue by jasiu512** [reicast/reicast-emulator#1178] opened 2018-06-12 16:31 UTC
Android 8.0
Huawei Mate 10 Pro
Gamepad MODECOM  Vulcan flare. It is the same model like IPEGA PG 9021.

I saw an earlier topic but I do not see a solution. Although the buttons can be defined in the emulator settings, they do not work during the game. Is there any solution?

**Comment by LoungeKatt** [comment] 2018-06-12 16:36
Duplicate of https://github.com/reicast/reicast-emulator/issues/1039

**Closed by LoungeKatt** 2018-06-12 16:36 UTC
