### ISSUE TITLE
How do I get gameshark as boot disk on reicast

### ISSUE THREAD

**Issue by MasterGamingYT** [reicast/reicast-emulator#1272] opened 2018-08-10 00:18 UTC
Ok so I see this option called boot disk but how do I get something like gameshark as a boot disk, each time I edit it, it freezes, I'm just wondering...

**Comment by AbandonedCart** [comment] 2018-08-10 02:48
Duplicate of https://github.com/reicast/reicast-emulator/issues/1270

**Closed by AbandonedCart** 2018-08-10 02:48 UTC
