### ISSUE TITLE
Fix the snapcraft build

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1375] opened 2018-09-12 11:23 UTC
snapcraft build is broken because of c++11 usage

Just found out today, we haven't been pushing snapcraft builds since Aug21. 

We need to figure out how to fix this

build log
https://build.snapcraft.io/user/reicast/reicast-emulator/331060

:(

**Comment by baka0815** [comment] 2018-09-12 11:51
I can't see the issue:
> Your session has expired. Reload the page and sign in again.

**Comment by skmp** [comment] 2018-09-12 11:54
I guess it is private to members of the project? Did you try logging in to snapcraft via github?

Anyways

The error seems to be
```
/build/reicast/parts/reicast/build/shell/linux/../../core/imgread/common.cpp: In function ‘Disc* OpenDisc(const wchar*)’:
/build/reicast/parts/reicast/build/shell/linux/../../core/imgread/common.cpp:134:13: error: ‘nullptr’ was not declared in this scope
```

I've attached the log file here [snapcraft-log.txt](https://github.com/reicast/reicast-emulator/files/2374974/snapcraft-log.txt)

**Comment by baka0815** [comment] 2018-09-12 11:54
Looks like it was this commit: https://github.com/reicast/reicast-emulator/commit/1a4f597bd814915f1bd6f188c575cdfead4c73bc#diff-68060335a9647442c21edb5aa3cefc17

**Comment by AbandonedCart** [comment] 2018-09-13 10:42
The error says it is undefined, not that it doesn't exist.

**Comment by baka0815** [comment] 2018-09-13 12:31
However, can't we just skip the initialization and revert to ``Disc* rv;``?

**Comment by AbandonedCart** [comment] 2018-09-14 00:08
That could probably work, since a value is **always** set (preventing it from slipping by uninitialized)

**Comment by luserx0** [comment] 2018-09-21 10:50
- **i386 and amd64 builds restored in a functioning status**:
  * Tried adding the g++ directives "-std=c++0x" and "-std=gnu++0x" to our makefile; all nullptr build issues were solved but I was getting new ones :(
  * Tried changing the nullptr value to an initialized nullptr_t or sth; that's the stupidest thing I did. It got me straight up more build issues
  * At last, @baka0815 proposal made the build shut up and succeed :D 


* [Snapcraft builds](https://build.snapcraft.io/user/luserx0/reicast-emulator)
* [Branch with the changes](https://github.com/luserx0/reicast-emulator/commit/8d23d8652ce0f7cbf79422e4b30396b173f428d9)

- **arm64 and armhf build status**:
  * Still not fixed

- I'm writing an article on reicast and snapcraft where a lot of disrespect will take place about the goddamn platform and their "Canonical Distribution of Kubernetes" that takes 28 minutes to build reicast for amd64 targets :$

#1138 Schedule of deliverables will be priority next !
Currently investigating the stability of the existing build.

PS: Submitting PR this evening and closing issue

**Comment by AbandonedCart** [comment] 2018-09-21 10:55
@luserx0 If you're going to bash some platform, make sure to do it as yourself and not as a representative of the team unless you intend to have it reviewed first.

As for the fix, maybe next time you should trust that when two of us have already agreed that something is the likely solution, you should probably test that **first** and not as a **last** resort.

**Comment by luserx0** [comment] 2018-09-21 11:13
Thanks for your kind input.

**Comment by luserx0** [comment] 2018-09-21 16:28
PR Submitted, issue closed

**Comment by baka0815** [comment] 2018-09-21 17:18
If you specify something like "fixes #1375" in the pr description, the issue is automatically closed when thr pr is merged, tjere is no need for the extra step to close the pr manually.

**Comment by AbandonedCart** [comment] 2018-09-21 19:14
@baka0815 I was wondering how that happened before. Thanks for that.

**Comment by 6alileo** [comment] 2018-10-14 15:46
I'm getting this same error on an Odroid XU4

```
g++   -I/home/pigaming/RetroPie-Setup/tmp/build/reicast/shell/linux/../../core -I/home/pigaming/RetroPie-Setup/tmp/build/reicast/shell/linux/../../core/deps -I/home/pigaming/RetroPie-Setup/tmp/build/reicast/shell/linux/../../core/khronos  -D TARGET_BEAGLE -D TARGET_LINUX_ARMELv7 -DARM_HARDFP -fsingle-precision-constant -g -O3 -D RELEASE -c -D USES_HOMEDIR  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize -fomit-frame-pointer  -marm -mfpu=neon -mfloat-abi=hard -funroll-loops -march=armv7ve -mtune=cortex-a15.cortex-a7  -fno-rtti -fpermissive -fno-operator-names -D_GLIBCXX_USE_CXX11_ABI=0 -D USE_EVDEV `pkg-config --cflags alsa` -D USE_ALSA -D USE_OSS -DGLES /home/pigaming/RetroPie-Setup/tmp/build/reicast/shell/linux/../../core/imgread/common.cpp -o obj-dreamcast-odroidxu3/imgread/common.build_obj
/home/pigaming/RetroPie-Setup/tmp/build/reicast/shell/linux/../../core/imgread/common.cpp: In function ‘Disc* OpenDisc(const wchar*)’:
/home/pigaming/RetroPie-Setup/tmp/build/reicast/shell/linux/../../core/imgread/common.cpp:134:13: error: ‘nullptr’ was not declared in this scope
  Disc* rv = nullptr;
             ^
Makefile:384: recipe for target 'obj-dreamcast-odroidxu3/imgread/common.build_obj' failed
make: *** [obj-dreamcast-odroidxu3/imgread/common.build_obj] Error 1
make: *** Waiting for unfinished jobs....
/tmp/ccdTssPj.s: Assembler messages:
/tmp/ccdTssPj.s:173506: Warning: ignoring changed section attributes for .text
/opt/retropie/emulators
Could not successfully build reicast - Dreamcast emulator Reicast (/home/pigaming/RetroPie-Setup/tmp/build/reicast/shell/linux/reicast.elf not found).
```

Make file is modified to

`CXXFLAGS += -fno-rtti -fpermissive -fno-operator-names -D_GLIBCXX_USE_CXX11_ABI=0`

**Comment by luserx0** [comment] 2018-10-15 19:47
@baka0815 This issue has been foxed by the PR that fixes snapcraft issues. This is a closed issue. 
If you'd like you can review the PR.

**Comment by baka0815** [comment] 2018-10-16 09:00
Yes it's in some PR, and no it's **not** fixed, because the PR is not merged yet!

**Comment by dmiller423** [comment] 2018-10-24 15:42
nullptr is removed from master,  this was an oversight when code was remerged by @AbandonedCart from my original code.   C++11(+) may be used in the future once the minimum platform is OK'd for Android.  Build flags will be set appropriately.

**Closed** 2018-11-04 11:35 UTC
Labels: Bug, Good First Issue, Help Wanted
