### ISSUE TITLE
reicast r19.07.3 still crashing on some android devices

### ISSUE THREAD

**Issue by ghost** [reicast/reicast-emulator#1688] opened 2019-07-17 03:04 UTC
**_Screenshots_**
![FB_IMG_15633326128430376](https://user-images.githubusercontent.com/37603562/61344127-c2449480-a882-11e9-8071-370e198a1f59.jpg)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by skmp** [comment] 2019-07-20 08:47
Which android devices are those?

**Comment by ghost** [comment] 2019-07-20 11:17
https://www.google.com/amp/s/m.gsmarena.com/xiaomi_redmi_6a-ampp-9217.php

**Comment by ghost** [comment] 2019-07-21 00:43
Same with Alcatel pop 4 + . Is it because my device is weaker?

**Comment by spielvan** [comment] 2019-07-21 18:07
The same happens in my box android tv MX3-G, S912 with android 5.1.1 GPU Mali450

**Comment by ghost** [comment] 2019-07-22 05:40
@spielvan didn't crash on my android phone same with your SoC Mali-450 and Android 5.1 🤔

**Comment by spielvan** [comment] 2019-07-22 18:53
> @spielvan didn't crash on my android phone same with your SoC Mali-450 and Android 5.1

It's weird indeed, until this version works perfectly.

[https://1.bp.blogspot.com/-vkOkwueG4z0/XTYFiNddvZI/AAAAAAAADa8/XkQyCB_1hg4D-NMu1qAd2eMhbtLAgy0dwCLcBGAs/s1600/Screenshot_2019-07-22-13-19-29.png](url)

**Comment by ghost** [comment] 2019-07-26 14:43
It started working for me, I had to adjust it in settings.

**Comment by ghost** [comment] 2019-07-28 06:39
@JohannesX what's your phone specs, and what settings did you change in reicast?

**Comment by ghost** [comment] 2019-07-28 07:36
It only has 1.5 GB of ram and I changed it to unstable optimizations and frame skip to 5

**Comment by ghost** [comment] 2019-07-28 14:57
@JohannesX the main issue here is that the reicast automatically close after clicking it so the user can't change the settings inside the app.

Maybe your issue is about lag not crash 🤷

**Comment by ghost** [comment] 2019-07-28 21:01
Yeah I could always get it to boot the bios and maybe the title screen of the game but wasn’t getting any gameplay. So I would still consider that crashing. Would you?

**Comment by skmp** [comment] 2019-07-29 13:44
Good news on this: I was able to replicate at least one crash on my pixel3a.
Bad news: it looks like some rather complicated bug

**Comment by ghost** [comment] 2019-07-30 08:08
@skmp but it's fixable? 😅

**Comment by skmp** [comment] 2019-07-30 09:01
#1710 is the fix for the bug I found. Will release beta as soon as it passes CI.

**Comment by skmp** [comment] 2019-07-30 09:29
Beta `r19.07.3-52-gfe2ba8cc` should be out within 1h, please test and report back

**Comment by ghost** [comment] 2019-07-30 10:30
I will test later ^_^

**Comment by ghost** [comment] 2019-07-30 11:08
@skmp still no beta update in my playstore 🤔
![Screenshot_2019-07-30-19-06-55](https://user-images.githubusercontent.com/37603562/62124671-5e4bb280-b2fd-11e9-86b8-3590947bc750.png)

**Comment by skmp** [comment] 2019-07-30 16:29
Closing this on favor of #1709

**Comment by skmp** [comment] 2019-07-30 16:29
Seems to be an android 5.x bug, not a bug in reicast. Will try to work around it

**Closed as completed by skmp** 2019-07-30 16:29 UTC
