### ISSUE TITLE
[linux] controller does not work

### ISSUE THREAD

**Issue by legluondunet** [reicast/reicast-emulator#862] opened 2015-11-13 09:40 UTC
Hello,

my controller does not work with Reicast. In the log file I saw this lines:

evdev: Trying to open device at '/dev/input/event0'
evdev: open: Permission denied

The complete log:

./reicast.elf 
Config dir is: /home/legluondunet/.reicast/
Data dir is:   /home/legluondunet/.reicast/
Personality: 00000000
Updated personality: 00000000
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: 66D70000, aram: 86d70000, vram: 6AD70000, ram: 72D70000
Resetting mem
Mem alloc successful!
libwebsockets test server - (C) Copyright 2010-2013 Andy Green <andy@warmcat.com> - licensed under LGPL2.1
Malformed entry on config - ignoring @ 39(ElfFile)
Initial logging level 7
Library version: 1.3 c11b847
IPV6 not compiled in
libev support not compiled in
 static allocation: 4488 + (16 x 1024 fds) = 20872 bytes
 canonical_hostname = tipingouin-home
 per-conn mem: 184 + 1554 headers + protocol rx buf
 Listening on port 5678
Found 10 matching FB configs.
Chosen visual ID = 0x24
Loaded /home/legluondunet/.reicast/data/dc_boot.bin as bootrom

Loaded /home/legluondunet/.reicast/data/dc_flash.bin as nvram

Using Recompiler
Auto-selected audio backend "alsa" (Advanced Linux Sound Architecture).
Initializing audio backend "alsa" (Advanced Linux Sound Architecture)...
recSh4 Init
Freeing fpcb

	 CodeCache addr: 0x4ac000 | from: 0x4ac000 | addr here: 0x4aa960
gdrom: Failed to open image "null"
Initialising empty vmu...
Sh4 Reset
evdev: Trying to open device at '/dev/input/event0'
evdev: open: Permission denied
evdev: Controller 2 disabled by config.
evdev: Controller 3 disabled by config.
evdev: Controller 4 disabled by config.
Legacy Joystick input disabled by config.

cntx // fpcb offset: -68157440 // pc offset: -184 // pc A0000000
Get MemPtr unsupported area : addr=0xA0000000
Get MemPtr unsupported area : addr=0xA0000018
Sh4: i-cache invalidation A0000016
Freeing fpcb
recSh4:Dynarec Cache clear at A0000016
Get MemPtr unsupported area : addr=0x80000080
Get MemPtr unsupported area : addr=0x800000A8
Get MemPtr unsupported area : addr=0x800000BE
Get MemPtr unsupported area : addr=0x800000C6
Freeing fpcb
recSh4:Dynarec Cache clear at 8C0000DE
ALSA: underrun occurred
GL context version: 3.1
OSD: 6
Error opening /home/legluondunet/.reicast/data/buttons.png
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
VREG = 03 ARMRST 00
VREG = 03 ARMRST 01
VREG = 03 ARMRST 00
sh4io: Invalid read access @@ 00000030
Sh4: i-cache invalidation 8C00DD78
Freeing fpcb
recSh4:Dynarec Cache clear at 8C00DD78
DIV32S matched 1% @ 0x8C00CF78
DIV32S matched 100% @ 0x8C00CF7E
div32s 1/0/3
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
Sh4: i-cache invalidation 8C09E6A6
Freeing fpcb
recSh4:Dynarec Cache clear at 8C09E6A6
Sh4: i-cache invalidation AC09D990
Freeing fpcb
recSh4:Dynarec Cache clear at AC09D990
VREG = 03 ARMRST 00
new tactx
new tactx
DIV32S matched 1% @ 0x8C091086
DIV32S matched 100% @ 0x8C09108C
div32s 1/0/3
DIV32S matched 1% @ 0x8C0911E4
DIV32S matched 100% @ 0x8C0911EC
div32s 1/0/3
DIV32S matched 1% @ 0x8C09126E
DIV32S matched 1% @ 0x8C091278
VREG = 03 ARMRST 01
VREG = 03 ARMRST 01
VREG = 03 ARMRST 00
FOG TABLE Curve match: maxdev: 0.43 cents
new tactx
reicast git/n - 13.28 (0.00) - 75.32 - V: 37.66 (6.91, PAL480i50.00) R: 2.97+2.48 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.02 (0.00) - 99.83 - V: 49.92 (inf, PAL480i50.00) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
Sh4: i-cache invalidation AC09EC6E
Freeing fpcb
recSh4:Dynarec Cache clear at AC09EC6E
DIV32S matched 1% @ 0x8C00CF78
DIV32S matched 100% @ 0x8C00CF7E
div32s 1/0/3
DIV32S matched 1% @ 0x8C00D0D6
DIV32S matched 100% @ 0x8C00D0DE
div32s 1/0/3
DIV32S matched 1% @ 0x8C00D160
DIV32S matched 1% @ 0x8C00D16A
Sh4: i-cache invalidation 8C00DD78
Freeing fpcb
recSh4:Dynarec Cache clear at 8C00DD78
DIV32S matched 1% @ 0x8C00CF78
DIV32S matched 100% @ 0x8C00CF7E
div32s 1/0/3
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
Sh4: i-cache invalidation 8C09E6A6
Freeing fpcb
recSh4:Dynarec Cache clear at 8C09E6A6
Sh4: i-cache invalidation AC09D990
Freeing fpcb
recSh4:Dynarec Cache clear at AC09D990
VREG = 03 ARMRST 00
DIV32S matched 1% @ 0x8C091086
DIV32S matched 100% @ 0x8C09108C
div32s 1/0/3
DIV32S matched 1% @ 0x8C0911E4
DIV32S matched 100% @ 0x8C0911EC
div32s 1/0/3
DIV32S matched 1% @ 0x8C09126E
DIV32S matched 1% @ 0x8C091278
VREG = 03 ARMRST 01
VREG = 03 ARMRST 01
VREG = 03 ARMRST 00
DIV32S matched 1% @ 0x8C0294A6
DIV32S matched 100% @ 0x8C0294AC
div32s 1/0/3
reicast git/n - 10.17 (0.00) - 98.34 - V: 49.17 (1.34, PAL480i50.00) R: 36.26+0.50 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.00 (0.00) - 99.98 - V: 49.99 (1.00, PAL480i50.00) R: 49.01+0.98 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.04 (0.00) - 99.64 - V: 49.82 (1.00, PAL480i50.00) R: 49.82+0.00 VTX: 0.00 , MIPS: 0.00
x11: setting fullscreen to 1
reicast git/n - 9.96 (0.00) - 100.39 - V: 50.19 (1.00, PAL480i50.00) R: 49.70+0.49 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.04 (0.00) - 99.57 - V: 49.78 (1.00, PAL480i50.00) R: 49.29+0.50 VTX: 0.00 , MIPS: 0.00
reicast git/n - 9.96 (0.00) - 100.37 - V: 50.19 (1.00, PAL480i50.00) R: 50.19+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.04 (0.00) - 99.63 - V: 49.81 (1.00, PAL480i50.00) R: 49.81+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 9.94 (0.00) - 100.61 - V: 50.31 (1.00, PAL480i50.00) R: 50.31+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.04 (0.00) - 99.58 - V: 49.79 (1.00, PAL480i50.00) R: 49.79+0.00 VTX: 0.00 , MIPS: 0.00
Sh4: i-cache invalidation AC09EC6E
Freeing fpcb
recSh4:Dynarec Cache clear at AC09EC6E
Sh4: i-cache invalidation 8C00DD78
Freeing fpcb
recSh4:Dynarec Cache clear at 8C00DD78
DIV32S matched 1% @ 0x8C00CF78
DIV32S matched 100% @ 0x8C00CF7E
div32s 1/0/3
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
Sh4: i-cache invalidation 8C09E6A6
Freeing fpcb
recSh4:Dynarec Cache clear at 8C09E6A6
Sh4: i-cache invalidation AC09D990
Freeing fpcb
recSh4:Dynarec Cache clear at AC09D990
VREG = 03 ARMRST 00
DIV32S matched 1% @ 0x8C091086
DIV32S matched 100% @ 0x8C09108C
div32s 1/0/3
DIV32S matched 1% @ 0x8C0911E4
DIV32S matched 100% @ 0x8C0911EC
div32s 1/0/3
DIV32S matched 1% @ 0x8C09126E
DIV32S matched 1% @ 0x8C091278
VREG = 03 ARMRST 01
VREG = 03 ARMRST 01
VREG = 03 ARMRST 00
DIV32S matched 1% @ 0x8C0294A6
DIV32S matched 100% @ 0x8C0294AC
div32s 1/0/3
reicast git/n - 10.35 (0.00) - 96.61 - V: 48.30 (1.34, PAL480i50.00) R: 35.98+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.02 (0.00) - 99.81 - V: 49.90 (1.00, PAL480i50.00) R: 49.41+0.49 VTX: 0.00 , MIPS: 0.00
Fatal error : death by escape key
 in input_x11_handle -> ../../core/linux-dist/x11.cpp : 77 

Trappe pour point d'arrêt et de trace (core dumped)

Thank you for your help.
LGDN

config:
Ubuntu 15.10 Wily 64 bits
NVIDIA  GeForce GTX 770
official Ubuntu Nvidia drivers 340.93 resolution 1920x1080
Processor Intel i5-3570 3,4 Ghz
8 Go RAM

**Comment by Holzhaus** [comment] 2015-11-13 14:01
Well, you don't have the permission to access `/dev/input/event0`. You should consult your distro's support forums if you don't know how to fix this. Closing this, since it's not a bug.

**Closed by Holzhaus** 2015-11-13 14:01 UTC

**Comment by legluondunet** [comment] 2015-11-13 17:27
I added my user to the "input" group and now it works.
This is the command line:
$ sudo adduser legluondunet input

Hope it will help others  pingouins.

**Comment by legluondunet** [comment] 2015-11-13 18:24
To play with my Xbox 360 controller, I had to add the event number of my controller to the emu.cfg and move the "mappings" folder to /home/legluondunet/local/share/reicast folder.
To obtain the event number of your controller:
cat /proc/bus/input/devices
you obtain:
I: Bus=0003 Vendor=045e Product=028e Version=0100
N: Name="Microsoft X-Box 360 pad"
P: Phys=usb-0000:00:14.0-3.1/input0
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.1/1-3.1:1.0/input/input43
U: Uniq=
H: Handlers=event16 js0 

where 16 is the event number to report to /home/legluondunet/.config/reicast/emu.cfg
to this line:
evdev_device_id_1 = write your id number here

I wrote this little explanation for others pingouins who need help with Reicast controller.

LGDN.

**Comment by Holzhaus** [comment] 2015-11-13 23:20
`evtest` should work, too.
