### ISSUE TITLE
Crash to Home Screen when loading game

### ISSUE THREAD

**Issue by LiverRobo** [reicast/reicast-emulator#754] opened 2015-08-16 10:42 UTC
Got a problem a lot of people do. I keep getting booted back to the home screen in the latest Lollipop version. Here are some logs.

http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1439721621972.txt

**Comment by LoungeKatt** [comment] 2015-08-16 15:08
Have you tried this with the most recent build? Your logs are using the old tags, so it appears your version may be before a few changes that should have fixed that.

**Comment by LiverRobo** [comment] 2015-08-16 15:10
I'm having problems locating the new build on GitHub. It's not a site I'm familiar with.

**Comment by Holzhaus** [comment] 2015-08-16 15:17
You can find them here: http://builds.reicast.com/

**Comment by LiverRobo** [comment] 2015-08-16 15:55
Alright, it runs the intro splash, then boots me back to the game browser.

http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1439740373091.txt

**Comment by LoungeKatt** [comment] 2015-08-16 16:53
@Holzhaus This looks like https://github.com/reicast/reicast-emulator/issues/750

**Comment by LoungeKatt** [comment] 2015-08-16 16:58
```I/reicast (32343): SIGSEGV @ 0x0 (fault_handler+0x0x5eea76ec) ... 0x0 -> was not in vram```

**Comment by LiverRobo** [comment] 2015-08-16 17:56
So... what does that mean?

**Comment by LoungeKatt** [comment] 2015-08-16 22:33
It means it is already being researched.

**Comment by LiverRobo** [comment] 2015-08-20 03:36
Got some new logs if they help.

http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1440041745652.txt

**Comment by LoungeKatt** [comment] 2015-08-20 05:48
Looks like this is a very different issue. 

@skmp this appears to be another one where it can't allocate the memory addresses

**Comment by skmp** [comment] 2015-08-20 05:54
This happens wayy too late to be an allocation issue. I've had multiple reports of it though on facebook. @LiverRobo which version are you running, exactly? Do you remember the # you downloaded? (This might also be visible on the about section, I forget). Also, can you please try with the latest version, [f83130b](http://reicast-builds.s3.amazonaws.com/builds/heads/master-f83130b/reicast-android-debug-f83130b.apk) and report back w/ a logfile if it still crashes?

**Comment by skmp** [comment] 2015-08-20 05:55
@LoungeKatt I don't tihnk it's realted to #750, however that issue should be fixed now

**Comment by LiverRobo** [comment] 2015-08-20 06:58
@skmp It is version f83130b.

**Comment by skmp** [comment] 2015-08-20 07:22
Aww, perfect. Thanks. I'll try to look into it the following days then...

On Thu, Aug 20, 2015 at 8:58 AM, LiverRobo <notifications@github.com> wrote:

> @skmp <https://github.com/skmp> It is version f83130b
> <https://github.com/reicast/reicast-emulator/commit/f83130b84ba6353c72a7400c8a304f382d84eca2>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/754#issuecomment-132912109>
> .
>



-- 
~skmp

**Comment by LiverRobo** [comment] 2015-08-20 07:45
Basically, @skmp, it's the same problem I had a handful of revisions back. Not the one I originally posted about, mind you.

**Comment by LoungeKatt** [comment] 2015-08-20 13:44
I need to revisit that memory allocation table logging. It should only be printing that table when that's an actual issue. It's not supposed to be misleading.

**Comment by LiverRobo** [comment] 2015-08-20 17:10
Alright, installed today's first revision. Still getting booted back to the file browser after the Dreamcast logo splash.

http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1440090535907.txt

Should I be clearing cache and reinstalling each new version?

**Comment by skmp** [comment] 2015-08-27 15:20
From facebook "Reicast. The problem that the games back to the menu screen after bios discovered that the problem is solved when disables dynamic recompiling option (dynamic recompilation). Only the speed of the games are very slow. I do not know how to log this problem, but there is a hint of a possible solution: make the emulator does not crash when the dynamic recompilation is enabled. Tested roms cdi. Sonic Adventure, Sonic Adventure 2 and MDK2. Tested on Galaxy S4, Android 5.0.2. All the latest builds exhibit the same problem." which points towards a dynarec problem. @LiverRobo can you try w/ dynarec off?

**Comment by LiverRobo** [comment] 2015-08-27 18:14
Yep, crash resolved. Now to work on game speed.

http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1440699188060.txt

**Comment by d1noxd** [comment] 2017-06-03 19:57
Who found fix?!!

**Comment by skmp** [comment] 2018-07-15 11:14
Please use the latest beta from #1208. Issue looks resolved anyway.

**Closed by skmp** 2018-07-15 11:14 UTC

**Comment by dogerizergaming** [comment] 2020-02-19 23:43
Mine crashes on Daytona USA
