### ISSUE TITLE
Soul Calibur freezes after 6 minutes on Shield portable

### ISSUE THREAD

**Issue by hooby3dfx** [reicast/reicast-emulator#622] opened 2015-03-31 03:55 UTC
**Game:** Soul Calibur
**Device:** Shield portable
**Android version:** 4.4.2
**Reicast version:** https://github.com/reicast/reicast-emulator/commit/ebabdee
**Frequency:** Always
**Description:**
Either playing the game or just letting it sit in attract mode, the emulator freezes after about 6 and a half minutes.
**Steps to reproduce:**
1. Launch game
2. Let it run for 7 mins and it will freeze

**Comment by hooby3dfx** [comment] 2015-03-31 04:25
seems to be happening even sooner with sonic adventure 2, like within a minute

**Comment by skmp** [comment] 2015-03-31 05:44
Can you perhaps bisect the commit that broke it?

**Comment by hooby3dfx** [comment] 2015-03-31 13:37
you got it

**Comment by hooby3dfx** [comment] 2015-04-01 03:36
some progress! ci builds are so useful but many have issues with bios detection or upgrade failures. 

2015-01-07 04:45:35 commit #29496ac apk - this definitely has the issue
2015-01-07 01:22:29 commit #d055dbd apk
2015-01-06 19:59:52 commit #6ad25b8 apk
2015-01-06 14:19:16 commit #11e9ed1 apk
2014-12-30 11:29:54 commit #0783875 apk
2014-12-30 08:39:49 commit #78e4b3c apk
2014-12-25 06:27:58 commit #8e5f530 apk
2014-12-22 15:58:32 commit #2f584aa apk - this build does not have the issue

sonic is the easiest test since it freezes so soon.

**Comment by LoungeKatt** [comment] 2015-04-01 14:10
It makes no sense that the difference between 2f584aa and 8e5f530 is just network detection for the XML parser, which is only called by a feature that is disabled by default.

**Comment by hooby3dfx** [comment] 2015-04-01 15:29
there must have be something corrupting the builds then - try the ones from the site to see what i mean.

**Comment by skmp** [comment] 2015-05-07 18:40
Managed to reproduce this in windows. It's a deadlock somewhere in the multithreaded rendering logic.

**Comment by skmp** [comment] 2015-05-07 20:04
Fixed in 4b46de89bba9b51bc9691880037a6ff46b7f0b03. Please tests from builds.reicast.com ~

**Comment by skmp** [comment] 2015-05-07 21:23
Actual build is http://reicast-builds.s3.amazonaws.com/builds/heads/master-c25ce04/reicast-android-debug-c25ce04.apk

**Comment by skmp** [comment] 2015-05-07 23:28
Ok, we have at least a 3rd party verification that this is fixed, so closing. Please test and comment/re-open as appropriate.

**Closed by skmp** 2015-05-07 23:28 UTC
Labels: 1 - Ready, release-blocker

**Comment by BonzaiThePenguin** [comment] 2015-05-07 23:37
Yep, this report appears to be identical to mine, which definitely seems to be resolved (the freezing, at least). Really strange that the freezes first appeared in a different build for them, especially one that didn't really change anything.

**Comment by BonzaiThePenguin** [comment] 2015-05-07 23:42
Oh wait, this is the 6.5 minute problem. This one seems to be resolved then regressed all the time.
