### ISSUE TITLE
Record of Lodoss War, hangs during the first battle [dynarec/div0]

### ISSUE THREAD

**Issue by ricardo85x** [reicast/reicast-emulator#84] opened 2014-01-06 22:40 UTC
The game hangs during the first battle.

Device: Nvidia Shield
Reicast: R5
Format: GDI image.

**Comment by ricardo85x** [comment] 2015-01-23 14:56
Any news about that?
I just tried it out with the latest build and have the same problem.
thanks

**Comment by Deityfierezy** [comment] 2015-02-01 13:28
try to download this and put in the folder where is your emulator and say yes to all  sorry for my english is to bad http://nulldc.googlecode.com/files/nullDC_104_r136.7z if the link doesnt work say me

**Comment by ricardo85x** [comment] 2015-02-01 19:45
Hi @Deityfierezy 

Are you sure? there are windows files in this 7z.
I am testing it on a android 4 device.
I did copy this files to my device and got the same result

Thanks

**Comment by Deityfierezy** [comment] 2015-02-01 22:57
im sorry im having the same truble with nulldc for the pc and this resolve it,

**Comment by SlavMFM** [comment] 2016-03-29 15:57
It helped me too! Thank you very much!

**Comment by Bururian** [comment] 2017-06-28 20:25
@Deityfierezy 
Can you re-link that file? It's no longer valid. I'm experiencing the same issue with freezing on the first fight in NullDC with this game. I'm using a laptop with Win7 and the latest NullDC release.

**Comment by Deityfierezy** [comment] 2017-06-28 20:30
I will see if i have it, it was 2 years ago.

**Comment by Bururian** [comment] 2017-06-28 20:34
@Deityfierezy I understand. Thanks for the quick reply.

**Comment by Deityfierezy** [comment] 2017-06-28 21:18
i dont have it anymore, but i think i found something, if it works i tell you (probably tomorrow)

**Comment by Bururian** [comment] 2017-06-28 21:23
Thanks. As per above, I disable the Dynarec.Enabled line in the CFG file and it bypasses the issue at the cost of game speed. For me, all scripted battles so far cause the game to freeze when it is enabled. All on field battles haven't posed a problem so far, so I just save before I enter a scripted battle or boss fight to make sure I do not lose progress.

**Comment by Deityfierezy** [comment] 2017-06-29 04:29
Well i cant remember wath files where, but there is my emulator with evrything all configured: https://mega.nz/#!VQ9THDKT!SX13ommbgUah-kZzjCI_oBZu9HgT5SOWCd8ET5r78O8
 I played a little bit of the game and i didnt see any problem, hope this is helpful, just extract the files in the same directory as the emulator, or in other place, or extract the newest emulator and then this in the same directory, just try, (i recommend trying one of the last 2) 
Sorry for my english

**Comment by Bururian** [comment] 2017-06-29 04:39
Perfect. This bypassed the first fight without a freeze. I'll continue playing with this and let you know if anything else arises. Thank you for all the help.

**Comment by Shootinshark** [comment] 2017-07-11 18:08
Thank you for the download, I was also looking to play Record of Lodoss War (Same issues).

I have found that the smithy crashes if you try to upgrade too fast (or sometimes just randomly), but other than that nothing has crashed so far :)

**Comment by blackman91** [comment] 2018-06-08 06:01
Anyway to fix this on Reicast for Android, it happens in both r6 and r7.

**Comment by LoungeKatt** [comment] 2018-06-08 08:51
According to the other posts, turning dynarec off may help bypass the freezes for now.

**Comment by skmp** [comment] 2018-06-09 14:46
Sounds like really a combination of factors. Disabling div matching fixes it as a workaround - if anyone is up to trying that it would be great. We could make the div a flag as a temporary fix.

**Comment by MarcoEstevez** [comment] 2018-07-10 21:07
Any news here? I started this game on Ricast retroarch core and game hanged on the first battle, I was about to apen an Issue when I saw this one.

**Comment by blackman91** [comment] 2018-07-10 23:42
Were you able to finish the game without freezes?

**Comment by Shootinshark** [comment] 2018-07-11 00:00
It froze when I went through the weapon upgrade screen too fast by spam upgrading my weapon. You'll see it when it happens :)
________________________________

**Comment by blackman91** [comment] 2018-07-11 00:10
I meant in battles, I get freezes in battles.

**Comment by Shootinshark** [comment] 2018-07-11 00:16
I only got the freeze in the first battle, but it dissapeared after the first one.

Other than literal freezes. Like, the actual elemental freeze. God, I hate the ice caves.
________________________________

**Comment by blackman91** [comment] 2018-07-11 00:18
What reicast version did you use? Any way you could test again using latest beta build?
https://github.com/reicast/reicast-emulator/issues/1208

**Comment by Shootinshark** [comment] 2018-07-11 00:20
I don't have any of it on my new pc. Haven't played Lodoss since last summer :)
________________________________

**Comment by LoungeKatt** [comment] 2018-07-12 16:10
The issue was related to dynarec and Nvidia Shield **is** and Android device, so it has been confirmed on mobile already.

**Comment by skmp** [comment] 2018-07-14 02:29
Closing this in favor of reicast/reicast-gamedb#14

**Closed by skmp** 2018-07-14 02:29 UTC
Labels: Bug, Limitation, Move to GameDB

**Comment by blackman91** [comment] 2018-08-10 20:13
The hanging still happens on latest beta and on fh master builds, any luck with the proposed solution guys? This is one of the great dreamcast games that no emu can play without freezing in scripted battles, it even freezes on RetroArch core.
Maybe @flyinghead can solve it too?

**Comment by AbandonedCart** [comment] 2018-08-10 21:35
In regards to the comment by @helloray, it appears we no longer return 0 from that function anyway.
```
u32 MatchDiv32(u32 pc , Sh4RegType &reg1,Sh4RegType &reg2 , Sh4RegType &reg3)
{

	u32 v_pc=pc;
	u32 match=1;
	for (int i=0;i<32;i++)
	{
		u16 opcode=ReadMem16(v_pc);
		v_pc+=2;
		if ((opcode&MASK_N)==ROTCL_KEY)
		{
			if (reg1==NoReg)
				reg1=(Sh4RegType)GetN(opcode);
			else if (reg1!=(Sh4RegType)GetN(opcode))
				break;
			match++;
		}
		else
		{
			//printf("DIV MATCH BROKEN BY: %s\n",OpDesc[opcode]->diss);
			break;
		}
		
		opcode=ReadMem16(v_pc);
		v_pc+=2;
		if ((opcode&MASK_N_M)==DIV1_KEY)
		{
			if (reg2==NoReg)
				reg2=(Sh4RegType)GetM(opcode);
			else if (reg2!=(Sh4RegType)GetM(opcode))
				break;
			
			if (reg2==reg1)
				break;

			if (reg3==NoReg)
				reg3=(Sh4RegType)GetN(opcode);
			else if (reg3!=(Sh4RegType)GetN(opcode))
				break;
			
			if (reg3==reg1)
				break;

			match++;
		}
		else
			break;
	}
	
	return match;
}
```

**Comment by blackman91** [comment] 2018-08-14 00:58
Apparently the issue is fixed with this:
https://github.com/libretro/reicast-emulator/pull/206

Could that be done in standalone reicast?

**Comment by blackman91** [comment] 2018-08-14 08:58
Just tested latest flyinghead/mymaster build and the issue seems to be fixed, tested on the first scripted battles and it no longer freezes:
https://github.com/reicast/reicast-emulator/commit/a7cfa1f

Great job!
