### ISSUE TITLE
Play Store version worked great with the CDI format, but the latest CI build crashes. What broke?

### ISSUE THREAD

**Issue by BonzaiThePenguin** [reicast/reicast-emulator#593] opened 2015-01-23 03:17 UTC
I heard the CDI format doesn't work well with Reicast, but was confused since I had been using CDIs and it worked great. The latest CI build fixed a lot of video glitches and has more settings available, but doesn't support the CDI format anymore. Odd!

**Comment by LoungeKatt** [comment] 2015-01-23 03:38
This is a duplicate of #592

**Closed** 2015-01-23 03:38 UTC
