### ISSUE TITLE
will not leave off where I that

### ISSUE THREAD

**Issue by sabula310** [reicast/reicast-emulator#833] opened 2015-09-13 18:18 UTC
When you turn off your phone it exit the game out when you turn it back on your in the main  u
It on my Samsung tab 4 and I ask the developer to fix they say it impossible  

I was like fuck this  not helping!

**Comment by Holzhaus** [comment] 2015-09-14 01:49
Punctuation mark and a more meaningful title would be helpful. I honestly don't understand what you're trying to tell us.

**Comment by hooby3dfx** [comment] 2015-09-14 12:43
No save state.
There is already an issue for this.

**Comment by Holzhaus** [comment] 2015-09-14 15:08
Ok, so this is a dupe of #301. Closing this.

**Closed by Holzhaus** 2015-09-14 15:08 UTC
Labels: duplicate
